In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('dataset.csv')
data.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
data = data.fillna(0)

In [4]:
data['Disease'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [5]:
import category_encoders as ce
encoder= ce.OrdinalEncoder(cols=['Disease'],return_df=True,
                           mapping=[{'col':'Disease',
'mapping':{'Allergy':1, 'GERD':2, 'Chronic cholestasis':3,
       'Drug Reaction':4, 'Peptic ulcer diseae':5, 'AIDS':6, 'Diabetes ':7,
       'Gastroenteritis':8, 'Bronchial Asthma':9, 'Hypertension ':10, 'Migraine':11,
       'Cervical spondylosis':12, 'Paralysis (brain hemorrhage)':13, 'Jaundice':14,
       'Malaria':15, 'Chicken pox':16, 'Dengue':17, 'Typhoid':18, 'hepatitis A':19,
       'Hepatitis B':20, 'Hepatitis C':21, 'Hepatitis D':22, 'Hepatitis E':23,
       'Alcoholic hepatitis':24, 'Tuberculosis':25, 'Common Cold':26, 'Pneumonia':27,
       'Dimorphic hemmorhoids(piles)':28, 'Heart attack':29, 'Varicose veins':30,
       'Hypothyroidism':31, 'Hyperthyroidism':32, 'Hypoglycemia':33,
       'Osteoarthristis':34, 'Arthritis':35,
       '(vertigo) Paroymsal  Positional Vertigo':36, 'Acne':37,
       'Urinary tract infection':38, 'Psoriasis':39, 'Impetigo':40,'Fungal infection':41}}])

data = encoder.fit_transform(data)

c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


In [6]:
data.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0       41     itching              skin_rash   nodal_skin_eruptions   
1       41   skin_rash   nodal_skin_eruptions    dischromic _patches   
2       41     itching   nodal_skin_eruptions    dischromic _patches   
3       41     itching              skin_rash    dischromic _patches   
4       41     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches         0         0         0         0         0   
1                     0         0         0         0         0         0   
2                     0         0         0         0         0         0   
3                     0         0         0         0         0         0   
4                     0         0         0         0         0         0   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

  Symptom_16 Symptom_17  
0          0          0  
1          0          0  
2          0          0  
3          0          0  
4          0          0

In [7]:
data['Symptom_1'].unique()

array(['itching', ' skin_rash', ' continuous_sneezing', ' shivering',
       ' stomach_pain', ' acidity', ' vomiting', ' indigestion',
       ' muscle_wasting', ' patches_in_throat', ' fatigue',
       ' weight_loss', ' sunken_eyes', ' cough', ' headache',
       ' chest_pain', ' back_pain', ' weakness_in_limbs', ' chills',
       ' joint_pain', ' yellowish_skin', ' constipation',
       ' pain_during_bowel_movements', ' breathlessness', ' cramps',
       ' weight_gain', ' mood_swings', ' neck_pain', ' muscle_weakness',
       ' stiff_neck', ' pus_filled_pimples', ' burning_micturition',
       ' bladder_discomfort', ' high_fever'], dtype=object)

In [8]:
encoder= ce.OrdinalEncoder(cols=['Symptom_1'],return_df=True,
                           mapping=[{'col':'Symptom_1',
'mapping':{'itching':1, ' skin_rash':2, ' continuous_sneezing':3, ' shivering':4,
       ' stomach_pain':5, ' acidity':6, ' vomiting':7, ' indigestion':8,
       ' muscle_wasting':9, ' patches_in_throat':10, ' fatigue':11,
       ' weight_loss':12, ' sunken_eyes':13, ' cough':14, ' headache':15,
       ' chest_pain':16, ' back_pain':17, ' weakness_in_limbs':18, ' chills':19,
       ' joint_pain':20, ' yellowish_skin':21, ' constipation':22,
       ' pain_during_bowel_movements':23, ' breathlessness':24, ' cramps':25,
       ' weight_gain':26, ' mood_swings':27, ' neck_pain':28, ' muscle_weakness':29,
       ' stiff_neck':30, ' pus_filled_pimples':31, ' burning_micturition':32,
       ' bladder_discomfort':33, ' high_fever':34}}])

data = encoder.fit_transform(data)

c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


In [9]:
data.head()

Disease  Symptom_1              Symptom_2              Symptom_3  \
0       41          1              skin_rash   nodal_skin_eruptions   
1       41          2   nodal_skin_eruptions    dischromic _patches   
2       41          1   nodal_skin_eruptions    dischromic _patches   
3       41          1              skin_rash    dischromic _patches   
4       41          1              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches         0         0         0         0         0   
1                     0         0         0         0         0         0   
2                     0         0         0         0         0         0   
3                     0         0         0         0         0         0   
4                     0         0         0         0         0         0   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

  Symptom_16 Symptom_17  
0          0          0  
1          0          0  
2          0          0  
3          0          0  
4          0          0

In [10]:
data['Symptom_2'].unique()

array([' skin_rash', ' nodal_skin_eruptions', ' shivering', ' chills',
       ' acidity', ' ulcers_on_tongue', ' vomiting', ' yellowish_skin',
       ' stomach_pain', ' loss_of_appetite', ' indigestion',
       ' patches_in_throat', ' high_fever', ' weight_loss',
       ' restlessness', ' sunken_eyes', ' dehydration', ' cough',
       ' chest_pain', ' dizziness', ' headache', ' weakness_in_limbs',
       ' neck_pain', ' weakness_of_one_body_side', ' fatigue',
       ' joint_pain', ' lethargy', ' nausea', ' abdominal_pain',
       ' pain_during_bowel_movements', ' pain_in_anal_region',
       ' breathlessness', ' sweating', ' cramps', ' bruising',
       ' weight_gain', ' cold_hands_and_feets', ' mood_swings',
       ' anxiety', ' knee_pain', ' stiff_neck', ' swelling_joints',
       ' pus_filled_pimples', ' blackheads', ' bladder_discomfort',
       ' foul_smell_of urine', ' skin_peeling', ' blister'], dtype=object)

In [11]:
encoder= ce.OrdinalEncoder(cols=['Symptom_2'],return_df=True,
                           mapping=[{'col':'Symptom_2',
'mapping':{' skin_rash':2, ' nodal_skin_eruptions':1, ' shivering':3, ' chills':4,
       ' acidity':6, ' ulcers_on_tongue':9, ' vomiting':7, ' yellowish_skin':8,
       ' stomach_pain':5, ' loss_of_appetite':10, ' indigestion':11,
       ' patches_in_throat':12, ' high_fever':13, ' weight_loss':14,
       ' restlessness':15, ' sunken_eyes':16, ' dehydration':17, ' cough':18,
       ' chest_pain':19, ' dizziness':20, ' headache':21, ' weakness_in_limbs':22,
       ' neck_pain':23, ' weakness_of_one_body_side':24, ' fatigue':25,
       ' joint_pain':26, ' lethargy':27, ' nausea':28, ' abdominal_pain':29,
       ' pain_during_bowel_movements':30, ' pain_in_anal_region':31,
       ' breathlessness':32, ' sweating':33, ' cramps':34, ' bruising':35,
       ' weight_gain':36, ' cold_hands_and_feets':37, ' mood_swings':38,
       ' anxiety':39, ' knee_pain':40, ' stiff_neck':41, ' swelling_joints':42,
       ' pus_filled_pimples':43, ' blackheads':44, ' bladder_discomfort':45,
       ' foul_smell_of urine':46, ' skin_peeling':47, ' blister':48}}])

data = encoder.fit_transform(data)

c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


In [12]:
data['Symptom_3'].unique()

array([' nodal_skin_eruptions', ' dischromic _patches', ' chills',
       ' watering_from_eyes', ' ulcers_on_tongue', ' vomiting',
       ' yellowish_skin', ' nausea', ' stomach_pain',
       ' burning_micturition', ' abdominal_pain', ' loss_of_appetite',
       ' high_fever', ' extra_marital_contacts', ' restlessness',
       ' lethargy', ' dehydration', ' diarrhoea', ' breathlessness',
       ' dizziness', ' loss_of_balance', ' headache',
       ' blurred_and_distorted_vision', ' neck_pain',
       ' weakness_of_one_body_side', ' altered_sensorium', ' fatigue',
       ' weight_loss', ' sweating', ' joint_pain', ' dark_urine',
       ' swelling_of_stomach', ' cough', ' pain_in_anal_region',
       ' bloody_stool', ' chest_pain', ' bruising', ' obesity',
       ' cold_hands_and_feets', ' mood_swings', ' anxiety', ' knee_pain',
       ' hip_joint_pain', ' swelling_joints', ' movement_stiffness',
       ' spinning_movements', ' blackheads', ' scurring',
       ' foul_smell_of urine', ' c

In [13]:
encoder= ce.OrdinalEncoder(cols=['Symptom_3'],return_df=True,
                           mapping=[{'col':'Symptom_3',
'mapping':{' nodal_skin_eruptions':1, ' dischromic _patches':2, ' chills':3,
       ' watering_from_eyes':4, ' ulcers_on_tongue':5, ' vomiting':6,
       ' yellowish_skin':7, ' nausea':8, ' stomach_pain':9,
       ' burning_micturition':10, ' abdominal_pain':11, ' loss_of_appetite':12,
       ' high_fever':13, ' extra_marital_contacts':14, ' restlessness':15,
       ' lethargy':16, ' dehydration':17, ' diarrhoea':18, ' breathlessness':19,
       ' dizziness':20, ' loss_of_balance':21, ' headache':22,
       ' blurred_and_distorted_vision':23, ' neck_pain':24,
       ' weakness_of_one_body_side':25, ' altered_sensorium':26, ' fatigue':27,
       ' weight_loss':28, ' sweating':29, ' joint_pain':30, ' dark_urine':31,
       ' swelling_of_stomach':32, ' cough':33, ' pain_in_anal_region':34,
       ' bloody_stool':35, ' chest_pain':36, ' bruising':37, ' obesity':38,
       ' cold_hands_and_feets':39, ' mood_swings':40, ' anxiety':41, ' knee_pain':42,
       ' hip_joint_pain':43, ' swelling_joints':44, ' movement_stiffness':45,
       ' spinning_movements':46, ' blackheads':47, ' scurring':48,
       ' foul_smell_of urine':49, ' continuous_feel_of_urine':50,
       ' skin_peeling':51, ' silver_like_dusting':52, ' blister':53,
       ' red_sore_around_nose':54}}])

data = encoder.fit_transform(data)

In [14]:
data['Symptom_4'].unique()

array([' dischromic _patches', 0, ' watering_from_eyes', ' vomiting',
       ' cough', ' nausea', ' loss_of_appetite', ' burning_micturition',
       ' spotting_ urination', ' passage_of_gases', ' abdominal_pain',
       ' extra_marital_contacts', ' lethargy', ' irregular_sugar_level',
       ' diarrhoea', ' breathlessness', ' family_history',
       ' loss_of_balance', ' lack_of_concentration',
       ' blurred_and_distorted_vision', ' excessive_hunger', ' dizziness',
       ' altered_sensorium', ' weight_loss', ' high_fever', ' sweating',
       ' headache', ' fatigue', ' dark_urine', ' yellowish_skin',
       ' yellowing_of_eyes', ' swelling_of_stomach',
       ' distention_of_abdomen', ' bloody_stool', ' irritation_in_anus',
       ' chest_pain', ' obesity', ' swollen_legs', ' mood_swings',
       ' restlessness', ' hip_joint_pain', ' swelling_joints',
       ' movement_stiffness', ' painful_walking', ' spinning_movements',
       ' scurring', ' continuous_feel_of_urine', ' silver_

In [15]:
encoder= ce.OrdinalEncoder(cols=['Symptom_4'],return_df=True,
                           mapping=[{'col':'Symptom_4',
'mapping':{' dischromic _patches':1,  0:0,' watering_from_eyes':2, ' vomiting':3,
       ' cough':4, ' nausea':5, ' loss_of_appetite':6, ' burning_micturition':7,
       ' spotting_ urination':8, ' passage_of_gases':9, ' abdominal_pain':10,
       ' extra_marital_contacts':11, ' lethargy':12, ' irregular_sugar_level':13,
       ' diarrhoea':14, ' breathlessness':15, ' family_history':16,
       ' loss_of_balance':17, ' lack_of_concentration':18,
       ' blurred_and_distorted_vision':19, ' excessive_hunger':20, ' dizziness':21,
       ' altered_sensorium':22, ' weight_loss':23, ' high_fever':24, ' sweating':25,
       ' headache':26, ' fatigue':27, ' dark_urine':28, ' yellowish_skin':29,
       ' yellowing_of_eyes':30, ' swelling_of_stomach':31,
       ' distention_of_abdomen':32, ' bloody_stool':33, ' irritation_in_anus':34,
       ' chest_pain':35, ' obesity':36, ' swollen_legs':37, ' mood_swings':38,
       ' restlessness':39, ' hip_joint_pain':40, ' swelling_joints':41,
       ' movement_stiffness':41, ' painful_walking':42, ' spinning_movements':43,
       ' scurring':44, ' continuous_feel_of_urine':45, ' silver_like_dusting':46,
       ' small_dents_in_nails':47, ' red_sore_around_nose':48,
       ' yellow_crust_ooze':49}}])

data = encoder.fit_transform(data)

In [16]:
data.head()

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4 Symptom_5 Symptom_6  \
0       41          1          2          1          1         0         0   
1       41          2          1          2          0         0         0   
2       41          1          1          2          0         0         0   
3       41          1          2          2          0         0         0   
4       41          1          2          1          0         0         0   

  Symptom_7 Symptom_8 Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13  \
0         0         0         0          0          0          0          0   
1         0         0         0          0          0          0          0   
2         0         0         0          0          0          0          0   
3         0         0         0          0          0          0          0   
4         0         0         0          0          0          0          0   

  Symptom_14 Symptom_15 Symptom_16 Symptom_17  
0          0          0          0          0  
1          0          0          0          0  
2          0          0          0          0  
3          0          0          0          0  
4          0          0          0          0

In [17]:
data['Symptom_5'].unique()

array([0, ' cough', ' chest_pain', ' loss_of_appetite', ' abdominal_pain',
       ' spotting_ urination', ' internal_itching', ' passage_of_gases',
       ' irregular_sugar_level', ' blurred_and_distorted_vision',
       ' family_history', ' mucoid_sputum', ' lack_of_concentration',
       ' excessive_hunger', ' stiff_neck', ' loss_of_balance',
       ' high_fever', ' yellowish_skin', ' headache', ' nausea',
       ' fatigue', ' dark_urine', ' yellowing_of_eyes',
       ' distention_of_abdomen', ' history_of_alcohol_consumption',
       ' breathlessness', ' sweating', ' irritation_in_anus',
       ' swollen_legs', ' swollen_blood_vessels', ' lethargy',
       ' dizziness', ' diarrhoea', ' swelling_joints', ' painful_walking',
       ' unsteadiness', ' small_dents_in_nails', ' inflammatory_nails',
       ' yellow_crust_ooze'], dtype=object)

In [18]:
encoder= ce.OrdinalEncoder(cols=['Symptom_5'],return_df=True,
                           mapping=[{'col':'Symptom_5',
'mapping':{0:0,' cough':1, ' chest_pain':2, ' loss_of_appetite':3, ' abdominal_pain':4,
       ' spotting_ urination':5, ' internal_itching':6, ' passage_of_gases':7,
       ' irregular_sugar_level':8, ' blurred_and_distorted_vision':9,
       ' family_history':10, ' mucoid_sputum':11, ' lack_of_concentration':12,
       ' excessive_hunger':13, ' stiff_neck':14, ' loss_of_balance':15,
       ' high_fever':16, ' yellowish_skin':17, ' headache':18, ' nausea':19,
       ' fatigue':20, ' dark_urine':21, ' yellowing_of_eyes':22,
       ' distention_of_abdomen':23, ' history_of_alcohol_consumption':24,
       ' breathlessness':25, ' sweating':26, ' irritation_in_anus':27,
       ' swollen_legs':28, ' swollen_blood_vessels':29, ' lethargy':30,
       ' dizziness':31, ' diarrhoea':32, ' swelling_joints':33, ' painful_walking':34,
       ' unsteadiness':35, ' small_dents_in_nails':36, ' inflammatory_nails':37,
       ' yellow_crust_ooze':38}}])

data = encoder.fit_transform(data)

c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


In [19]:
data['Symptom_6'].unique()

array([0, ' chest_pain', ' abdominal_pain', ' yellowing_of_eyes',
       ' internal_itching', ' blurred_and_distorted_vision', ' obesity',
       ' mucoid_sputum', ' stiff_neck', ' depression', ' yellowish_skin',
       ' dark_urine', ' nausea', ' diarrhoea', ' headache',
       ' loss_of_appetite', ' high_fever', ' constipation',
       ' family_history', ' history_of_alcohol_consumption',
       ' fluid_overload', ' breathlessness', ' swelled_lymph_nodes',
       ' sweating', ' malaise', ' swollen_blood_vessels',
       ' prominent_veins_on_calf', ' dizziness', ' puffy_face_and_eyes',
       ' fast_heart_rate', ' painful_walking', ' unsteadiness',
       ' inflammatory_nails'], dtype=object)

In [20]:
encoder= ce.OrdinalEncoder(cols=['Symptom_6'],return_df=True,
                           mapping=[{'col':'Symptom_6',
'mapping':{0:0,' chest_pain':1, ' abdominal_pain':2, ' yellowing_of_eyes':3,
       ' internal_itching':4, ' blurred_and_distorted_vision':5, ' obesity':6,
       ' mucoid_sputum':7, ' stiff_neck':8, ' depression':9, ' yellowish_skin':10,
       ' dark_urine':11, ' nausea':12, ' diarrhoea':13, ' headache':14,
       ' loss_of_appetite':15, ' high_fever':16, ' constipation':17,
       ' family_history':18, ' history_of_alcohol_consumption':19,
       ' fluid_overload':20, ' breathlessness':21, ' swelled_lymph_nodes':22,
       ' sweating':23, ' malaise':24, ' swollen_blood_vessels':25,
       ' prominent_veins_on_calf':26, ' dizziness':27, ' puffy_face_and_eyes':28,
       ' fast_heart_rate':29, ' painful_walking':30, ' unsteadiness':31,
       ' inflammatory_nails':32}}])

data = encoder.fit_transform(data)

In [21]:
data['Symptom_7'].unique()

array([0, ' yellowing_of_eyes', ' obesity', ' excessive_hunger',
       ' depression', ' irritability', ' dark_urine', ' abdominal_pain',
       ' muscle_pain', ' diarrhoea', ' loss_of_appetite', ' mild_fever',
       ' headache', ' nausea', ' constipation', ' yellow_urine',
       ' fluid_overload', ' breathlessness', ' sweating',
       ' swelled_lymph_nodes', ' malaise', ' phlegm',
       ' prominent_veins_on_calf', ' puffy_face_and_eyes',
       ' enlarged_thyroid', ' fast_heart_rate',
       ' blurred_and_distorted_vision'], dtype=object)

In [22]:
encoder= ce.OrdinalEncoder(cols=['Symptom_7'],return_df=True,
                           mapping=[{'col':'Symptom_7',
'mapping':{0:0,' yellowing_of_eyes':1, ' obesity':2, ' excessive_hunger':3,
       ' depression':4, ' irritability':5, ' dark_urine':6, ' abdominal_pain':7,
       ' muscle_pain':8, ' diarrhoea':9, ' loss_of_appetite':10, ' mild_fever':11,
       ' headache':12, ' nausea':13, ' constipation':14, ' yellow_urine':15,
       ' fluid_overload':16, ' breathlessness':17, ' sweating':18,
       ' swelled_lymph_nodes':19, ' malaise':20, ' phlegm':21,
       ' prominent_veins_on_calf':22, ' puffy_face_and_eyes':23,
       ' enlarged_thyroid':24, ' fast_heart_rate':25,
       ' blurred_and_distorted_vision':26}}])

data = encoder.fit_transform(data)

In [23]:
data['Symptom_8'].unique()

array([0, ' excessive_hunger', ' increased_appetite', ' irritability',
       ' visual_disturbances', ' abdominal_pain', ' muscle_pain',
       ' mild_fever', ' swelled_lymph_nodes', ' nausea',
       ' loss_of_appetite', ' diarrhoea', ' yellow_urine',
       ' yellowing_of_eyes', ' sweating', ' malaise', ' phlegm',
       ' chest_pain', ' enlarged_thyroid', ' brittle_nails',
       ' muscle_weakness', ' drying_and_tingling_lips'], dtype=object)

In [24]:
encoder= ce.OrdinalEncoder(cols=['Symptom_8'],return_df=True,
                           mapping=[{'col':'Symptom_8',
'mapping':{0:0,' excessive_hunger':1, ' increased_appetite':2, ' irritability':3,
       ' visual_disturbances':4, ' abdominal_pain':5, ' muscle_pain':6,
       ' mild_fever':7, ' swelled_lymph_nodes':8, ' nausea':9,
       ' loss_of_appetite':10, ' diarrhoea':11, ' yellow_urine':12,
       ' yellowing_of_eyes':13, ' sweating':14, ' malaise':15, ' phlegm':16,
       ' chest_pain':17, ' enlarged_thyroid':18, ' brittle_nails':19,
       ' muscle_weakness':20, ' drying_and_tingling_lips':21}}])

data = encoder.fit_transform(data)

In [25]:
data['Symptom_9'].unique()

array([0, ' increased_appetite', ' polyuria', ' visual_disturbances',
       ' swelled_lymph_nodes', ' malaise', ' loss_of_appetite',
       ' pain_behind_the_eyes', ' toxic_look_(typhos)', ' diarrhoea',
       ' mild_fever', ' yellowing_of_eyes', ' abdominal_pain', ' phlegm',
       ' throat_irritation', ' fast_heart_rate', ' chest_pain',
       ' brittle_nails', ' swollen_extremeties', ' muscle_weakness',
       ' irritability', ' slurred_speech', ' drying_and_tingling_lips'],
      dtype=object)

In [26]:
encoder= ce.OrdinalEncoder(cols=['Symptom_9'],return_df=True,
                           mapping=[{'col':'Symptom_9',
'mapping':{0:0,' increased_appetite':1, ' polyuria':2, ' visual_disturbances':3,
       ' swelled_lymph_nodes':4, ' malaise':5, ' loss_of_appetite':5,
       ' pain_behind_the_eyes':6, ' toxic_look_(typhos)':7, ' diarrhoea':8,
       ' mild_fever':9, ' yellowing_of_eyes':10, ' abdominal_pain':11, ' phlegm':12,
       ' throat_irritation':13, ' fast_heart_rate':14, ' chest_pain':15,
       ' brittle_nails':16, ' swollen_extremeties':17, ' muscle_weakness':18,
       ' irritability':19, ' slurred_speech':20, ' drying_and_tingling_lips':21}}])

data = encoder.fit_transform(data)

In [27]:
data['Symptom_10'].unique()

array([0, ' polyuria', ' malaise', ' red_spots_over_body',
       ' pain_behind_the_eyes', ' back_pain', ' belly_pain',
       ' toxic_look_(typhos)', ' yellowing_of_eyes', ' muscle_pain',
       ' receiving_blood_transfusion', ' acute_liver_failure',
       ' mild_fever', ' throat_irritation', ' redness_of_eyes',
       ' rusty_sputum', ' fast_heart_rate', ' swollen_extremeties',
       ' depression', ' irritability', ' abnormal_menstruation',
       ' slurred_speech'], dtype=object)

In [28]:
encoder= ce.OrdinalEncoder(cols=['Symptom_10'],return_df=True,
                           mapping=[{'col':'Symptom_10',
'mapping':{0:0,' polyuria':1, ' malaise':2, ' red_spots_over_body':3,
       ' pain_behind_the_eyes':4, ' back_pain':5, ' belly_pain':6,
       ' toxic_look_(typhos)':7, ' yellowing_of_eyes':8, ' muscle_pain':9,
       ' receiving_blood_transfusion':10, ' acute_liver_failure':11,
       ' mild_fever':12, ' throat_irritation':13, ' redness_of_eyes':14,
       ' rusty_sputum':15, ' fast_heart_rate':16, ' swollen_extremeties':17,
       ' depression':18, ' irritability':19, ' abnormal_menstruation':20,
       ' slurred_speech':21}}])

data = encoder.fit_transform(data)

In [29]:
data['Symptom_11'].unique()

array([0, ' red_spots_over_body', ' back_pain', ' malaise', ' belly_pain',
       ' muscle_pain', ' receiving_blood_transfusion',
       ' receiving_unsterile_injections', ' coma', ' acute_liver_failure',
       ' yellowing_of_eyes', ' swelled_lymph_nodes', ' redness_of_eyes',
       ' sinus_pressure', ' rusty_sputum', ' depression', ' irritability',
       ' abnormal_menstruation', ' palpitations'], dtype=object)

In [30]:
encoder= ce.OrdinalEncoder(cols=['Symptom_11'],return_df=True,
                           mapping=[{'col':'Symptom_11',
'mapping':{0:0,' red_spots_over_body':1, ' back_pain':2, ' malaise':3, ' belly_pain':4,
       ' muscle_pain':5, ' receiving_blood_transfusion':6,
       ' receiving_unsterile_injections':7, ' coma':8, ' acute_liver_failure':9,
       ' yellowing_of_eyes':10, ' swelled_lymph_nodes':11, ' redness_of_eyes':12,
       ' sinus_pressure':13, ' rusty_sputum':14, ' depression':15, ' irritability':16,
       ' abnormal_menstruation':17, ' palpitations':18}}])

data = encoder.fit_transform(data)

In [31]:
data['Symptom_12'].unique()

array([0, ' muscle_pain', ' malaise', ' receiving_unsterile_injections',
       ' stomach_bleeding', ' coma', ' swelled_lymph_nodes',
       ' sinus_pressure', ' runny_nose', ' irritability',
       ' abnormal_menstruation', ' palpitations'], dtype=object)

In [32]:
encoder= ce.OrdinalEncoder(cols=['Symptom_12'],return_df=True,
                           mapping=[{'col':'Symptom_12',
'mapping':{0:0,' muscle_pain':1, ' malaise':2, ' receiving_unsterile_injections':3,
       ' stomach_bleeding':4, ' coma':5, ' swelled_lymph_nodes':6,
       ' sinus_pressure':7, ' runny_nose':8, ' irritability':9,
       ' abnormal_menstruation':10, ' palpitations':11}}])

data = encoder.fit_transform(data)

In [33]:
data['Symptom_13'].unique()

array([0, ' red_spots_over_body', ' muscle_pain', ' stomach_bleeding',
       ' malaise', ' phlegm', ' runny_nose', ' congestion',
       ' abnormal_menstruation'], dtype=object)

In [34]:
encoder= ce.OrdinalEncoder(cols=['Symptom_13'],return_df=True,
                           mapping=[{'col':'Symptom_13',
'mapping':{0:0,' red_spots_over_body':1, ' muscle_pain':2, ' stomach_bleeding':3,
       ' malaise':4, ' phlegm':5, ' runny_nose':6, ' congestion':7,
       ' abnormal_menstruation':8}}])

data = encoder.fit_transform(data)

In [35]:
data['Symptom_14'].unique()

array([0, ' red_spots_over_body', ' phlegm', ' chest_pain', ' congestion'],
      dtype=object)

In [36]:
encoder= ce.OrdinalEncoder(cols=['Symptom_14'],return_df=True,
                           mapping=[{'col':'Symptom_14',
'mapping':{0:0,' red_spots_over_body':1, ' phlegm':2, ' chest_pain':3, ' congestion':4}}])

data = encoder.fit_transform(data)

In [37]:
data['Symptom_15'].unique()

array([0, ' chest_pain', ' blood_in_sputum', ' loss_of_smell'],
      dtype=object)

In [38]:
encoder= ce.OrdinalEncoder(cols=['Symptom_15'],return_df=True,
                           mapping=[{'col':'Symptom_15',
'mapping':{0:0,' chest_pain':1, ' blood_in_sputum':2, ' loss_of_smell':3}}])

data = encoder.fit_transform(data)

In [39]:
data['Symptom_16'].unique()

array([0, ' blood_in_sputum', ' loss_of_smell', ' muscle_pain'],
      dtype=object)

In [40]:
encoder= ce.OrdinalEncoder(cols=['Symptom_16'],return_df=True,
                           mapping=[{'col':'Symptom_16',
'mapping':{0:0,' blood_in_sputum':1, ' loss_of_smell':2, ' muscle_pain':3}}])

data = encoder.fit_transform(data)

In [41]:
data['Symptom_17'].unique()

array([0, ' muscle_pain'], dtype=object)

In [42]:
encoder= ce.OrdinalEncoder(cols=['Symptom_17'],return_df=True,
                           mapping=[{'col':'Symptom_17',
'mapping':{0:0,' muscle_pain':1}}])

data = encoder.fit_transform(data)

In [43]:
data.head(15)

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0        41          1          2          1          1          0          0   
1        41          2          1          2          0          0          0   
2        41          1          1          2          0          0          0   
3        41          1          2          2          0          0          0   
4        41          1          2          1          0          0          0   
5        41          2          1          2          0          0          0   
6        41          1          1          2          0          0          0   
7        41          1          2          2          0          0          0   
8        41          1          2          1          0          0          0   
9        41          1          2          1          1          0          0   
10        1          3          3          3          2          0          0   
11        1          4          4          4          0          0          0   
12        1          3          4          4          0          0          0   
13        1          3          3          4          0          0          0   
14        1          3          3          3          0          0          0   

    Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0           0          0          0           0           0           0   
1           0          0          0           0           0           0   
2           0          0          0           0           0           0   
3           0          0          0           0           0           0   
4           0          0          0           0           0           0   
5           0          0          0           0           0           0   
6           0          0          0           0           0           0   
7           0          0          0           0           0           0   
8           0          0          0           0           0           0   
9           0          0          0           0           0           0   
10          0          0          0           0           0           0   
11          0          0          0           0           0           0   
12          0          0          0           0           0           0   
13          0          0          0           0           0           0   
14          0          0          0           0           0           0   

    Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0            0           0           0           0           0  
1            0           0           0           0           0  
2            0           0           0           0           0  
3            0           0           0           0           0  
4            0           0           0           0           0  
5            0           0           0           0           0  
6            0           0           0           0           0  
7            0           0           0           0           0  
8            0           0           0           0           0  
9            0           0           0           0           0  
10           0           0           0           0           0  
11           0           0           0           0           0  
12           0           0           0           0           0  
13           0           0           0           0           0  
14           0           0           0           0           0

In [44]:
data = data.values

In [45]:
y = data[:,-18]
x = data[:,1:]

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(x, y, test_size = 0.20, random_state = 5)



from sklearn.ensemble import RandomForestRegressor
rt = RandomForestRegressor(n_estimators = 500, random_state = 0)
rt.fit(X_train,y_train)
print(rt.score(X_train, y_train)*100)
print(rt.score(X_val, y_val)*100)

99.9999213432214
99.99980999768292


In [47]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
print(lr.score(X_train, y_train))
print(lr.score(X_val, y_val))

0.5865496043662788
0.5828867952005037


In [48]:
from sklearn.tree import DecisionTreeRegressor
dec_tree = DecisionTreeRegressor(random_state = 0)
dec_tree.fit(X_train,y_train)
print(rt.score(X_train, y_train)*100)
print(rt.score(X_val, y_val)*100)

99.9999213432214
99.99980999768292
